FROM fabric8/java-alpine-openjdk11-jre
RUN addgroup -S spring && adduser -S spring -G spring
EXPOSE 8484
USER spring:spring
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]